### ISSUE TITLE
Shared Anchors not visible to other player.

### ISSUE THREAD

**Issue by NatanArt** [oculus-samples/Unity-SharedSpatialAnchors#10]
I've completed all of the setup mentioned in the documentation, and was able to successfully build to two Quest 2s. When testing, I was able to create local anchors and save them locally. When I tried to share the anchors, I would see the Wi-Fi symbol turn green and it would stay green which I took as a good thing. However when I looked at the logs, I saw that it said something along the lines of "the Sharing button was pressed" and then immediately it says "Saving anchors failed. Possible reasons include an unsupported device."

Can someone help me understand what that error means and how I might resolve it? I'm not really sure what needs to be fixed/changed since I followed the directions given.

**Comment by SteveOnorato** [comment]
"Saving anchors failed. Possible reasons include an unsupported device" is our generic failure message in the sample app.

Are you able to view the logcat?  It should show the detailed error information, hopefully one of the cases described here: https://developer.oculus.com/documentation/native/android/openxr-ssa-ts/
If none of those fix it for you, please reopen the issue and share the more specific error that you're seeing in logcat.
