### ISSUE TITLE
Trying to build the project, but the build cancels while doing some gradle stuff

### ISSUE THREAD

**Issue by lucaremberg** [oculus-samples/Unity-SharedSpatialAnchors#11]
Hi,
I am getting a build failure with the text: "A failure occured while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade See the console for details.". The details in the console saying this:
Note: Z:\Unity-SharedSpatialAnchors-main\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Package 'com.package.id' from AndroidManifest.xml is not a valid Java package name as 'package' is a Java keyword.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Maybe someone here can help me solve this problem.

**Comment by Yarwad** [comment]
Getting the same issue

**Comment by SteveOnorato** [comment]
In Unity, navigate to Oculus / Platform / Edit Settings.
Replace the placeholder Bundle Identifier "com.package.id" with a valid and unique Android package name like "com.steveonorato.ssa_sample" (following the naming rules at https://developer.android.com/studio/build/configure-app-module#set_the_application_id).

Sorry, this seems to be missing from the current documentation at https://developer.oculus.com/documentation/unity/unity-ssa-sf/ (there should be some improvements to that page coming shortly).

**Comment by lucaremberg** [comment]
thx for the help. now the bundle is building ^^
