### ISSUE TITLE
Synchronizing Heads and Hands

### ISSUE THREAD

**Issue by lucaremberg** [oculus-samples/Unity-SharedSpatialAnchors#14]
Hey,
is there an easy way to synchronize each players hands and heads, so the other players can see them too? Or do i need to implement it by myself?

**Comment by stephenm2022** [comment]
Hi @lucaremberg. There are many ways to visualize and synchronize player hands and head. Check out the Automatic Colocation demo (Assets/CoLocation/Scenes/CoLocatedSafety.unity) to see how we use passthrough avatars and Photon to achieve this functionality in the sample.
