### ISSUE TITLE
OnShareCompleteResult : -1006

### ISSUE THREAD

**Issue by ddhvr** [oculus-samples/Unity-SharedSpatialAnchors#15]
Hi,

I've checked the all posted issues and done the pre-setup (photon setup, oculus app created, user ID, user profile requested, add both accounts as the test user) but I'm still stuck on this error. Could anyone provide more info about this error code? I always got 1 correct user id and 0 from my both quest pro devices. I guess the 0 might be the reason why the sharing failed.

**Comment by stephenm2022** [comment]
Hi @ddhvr. OnShareCompleteResult code -1006 is thrown when the app is not entitled. 

Be sure that you:
- Create an app on the Meta Quest Org Manager.
- Add the app ID (found under "API" tab in the App Manager) in the Oculus Platform Settings in Unity.
- Confirm that you have been granted the User ID and User Profile permissions in the App Manager under Data user Checkup.
- Confirm that the test accounts (on device) are associated with the app on Meta Quest Org Manager.

**Comment by ddhvr** [comment]
Hi @stephenm2022, like I said I've done all the pre-setup in the project, but the error still exists.

**Comment by stephenm2022** [comment]
Hi @ddhvr. When you enter the Anchor Sharing Demo scene, do you see a valid Oculus username and id in the UI logs?

**Comment by ddhvr** [comment]
Hi @stephenm2022 ,

At first, no. But it became valid after a few days. I guess it might need some time to be entitled.

Updated: Anchor sharing is working now but it has a noticeable difference about 10 cm off. I've tried to make both headsets as close as possible when launching. Besides, the difference could become serious when used in different places, especially in a place that has many lights and reflections. So just wondering if there's anything I can do to improve the alignment. Right now I can only guarantee that the difference would be acceptable when using both in my seat and both headsets have similar guardian areas.

**Comment by AlwaysLELE** [comment]
Hello@stephenm2022, why is it that when I run this project scenario I have been unable to perform the functions of successfully saving local anchors, removing anchors, and aligning anchors. I can only create anchors and cubes. By the way, how to join a room?

**Comment by NicolasAbo17** [comment]
Be sure that both users are different and logged in Oculus. If is a development app check that both users can use the app, you can use test users or add them directly as developers. Maybe that helps.

**Comment by stephenm2022** [comment]
Hi @AlwaysLELE. It looks like the anchor save operations were successful; however, scene capture failed. Scene capture is only supported on the device and will fail over link. 

I can also see that authentication to the Platform SDK has failed (TestUser581), which will prevent anchor sharing from working. Be sure to create a Rift app and configure the Unity project with your Rift app ID for authentication over link.
