### ISSUE TITLE
OVRPlugin.ShareSpaces failed with result: Failure.

### ISSUE THREAD

**Issue by NicolasAbo17** [oculus-samples/Unity-SharedSpatialAnchors#16]
I started to get this error in my own personal project, I tried with the template and I still have it. 
Im using unity 2020. It seems the issue is caused by a new Oculus API but I'm not sure.

[OVRSpatialAnchor] [3a4ce480-625d-676c-0727-25193e5be04b] OVRPlugin.ShareSpaces failed with result: Failure.
UnityEngine.Debug:LogError (object)
OVRSpatialAnchor/Development:LogError (string) (at Assets/ThirdParty/Oculus/VR/Scripts/OVRSpatialAnchor.cs:1506)
OVRSpatialAnchor:InvokeMultiAnchorDelegate (ulong,OVRSpatialAnchor/OperationResult,OVRSpatialAnchor/MultiAnchorActionType) (at Assets/ThirdParty/Oculus/VR/Scripts/OVRSpatialAnchor.cs:942)
OVRSpatialAnchor:OnShareSpacesComplete (ulong,OVRSpatialAnchor/OperationResult) (at Assets/ThirdParty/Oculus/VR/Scripts/OVRSpatialAnchor.cs:1494)
OVRManager:UpdateHMDEvents () (at Assets/ThirdParty/Oculus/VR/Scripts/OVRManager.cs:2721)
OVRManager:Update () (at Assets/ThirdParty/Oculus/VR/Scripts/OVRManager.cs:2615)

**Comment by NicolasAbo17** [comment]
Actually I don't get that error anymore, Im doing it in a different machine. But now Im getting this when I try to do a build:

![image](https://github.com/oculus-samples/Unity-SharedSpatialAnchors/assets/38436508/0d9f222e-089a-4dc2-bfce-19b93328109b)


Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':launcher'.
> Could not resolve all artifacts for configuration ':launcher:classpath'.
   > Could not resolve com.android.tools.build:gradle:4.0.1.
     Required by:
         project :launcher
      > Could not resolve com.android.tools.build:gradle:4.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.0.1/gradle-4.0.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.0.1/gradle-4.0.1.pom'.
               > dl.google.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2020.3.42f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2020.3.42f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-6.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

**Comment by stephenm2022** [comment]
Hi @NicolasAbo17. Are you getting this error in the Unity sample or your own project? If using the sample, have you made any changes to the Unity or Oculus Integration SDK versions?

**Comment by NicolasAbo17** [comment]
It was an error I was getting using this but updating the oculus integration, but Im not sure I did it later and it worked. I dont have this error anymore so we can close the issue

**Comment by stephenm2022** [comment]
Hi @NicolasAbo17. I'm glad to hear you got it working. Please reach out again if you have any other questions or issues.
