### ISSUE TITLE
Photon Room Generation

### ISSUE THREAD

**Issue by TheWiselyBearded** [oculus-samples/Unity-SharedSpatialAnchors#24]
Hi all,

I notice the default behavior is to name a room after a user name:
`CreateNewRoomForLobby(PhotonPun.PhotonNetwork.NickName);`

This seemingly resulted in both players creating different rooms for joining. I tried changing this behavior such that the photon room is called "playground." 
So, `CreateNewRoomForLobby("playground");`
Despite this, both clients never seemingly join the same room. It shows no player is on the room, despite success messages and the same room name. 

I can verify that all shared app permissions are created correctly in the Meta Developer dashboard. Further, both devices (Quest 2 and Quest 3) are signed into Test User Accounts. 

**Is there something else I'm missing? How can I successfully get both players to enter the same room?**

**Comment by stephenm2022** [comment]
Hi @TheWiselyBearded. The CreateNewRoomForLobby method is only invoked when a user presses the create room button. Joining users should select the room they want to join from the room list after is has been created.

**Comment by TheWiselyBearded** [comment]
Hey, sorry I didn’t close this out. Actually, the issue is that in the photon settings configuration file for the project a region isn’t specified. If the developer doesn’t specify a region (usw for example) then it’ll auto-assign the server. So in my case, despite two headsets being on the same network with the same room name, they weren’t able to connect until updating the configuration file.
