### ISSUE TITLE
Error -1006 occurs on sharing anchor.

### ISSUE THREAD

**Issue by yutokun** [oculus-samples/Unity-SharedSpatialAnchors#4]
Possibly my mistake but I couldn't figure out. If anyone has any idea, please tell me.

# Expected

Shared Anchor appears on opponent headset.

# Actually

Error -1006 happens and nothing on opponent.

# To Reproduce

- Set Photon App ID, App Version, Fixed Region.
- Build and run this repository on 2 Meta Quest Pros.
- Load scene "Anchor Sharing Demo".
- Join same room on them.
- Create an anchor and press Share Anchor button.
- Error -1006 happens.

![IMG_0992](https://user-images.githubusercontent.com/8219697/208823907-9d388341-c765-41fe-a4e3-13e87ef77cf2.jpg)

**Comment by loic-all** [comment]
We had the same problem and after some research we found the solution.

You have to create an app on the Meta Quest Org Manager. 
When the app is created, you have to add the app ID (found under "API" tab in the App Manager) in the Oculus Platform Settings in Unity.
You also need to be granted the User ID and User Profile permissions in the App Manager under Data user Checkup.

**Comment by yutokun** [comment]
Thank you for sharing infomation.

I granted those permissions, then shared anchor appeared! Thank you so much.

**Comment by MPFabularisLab** [comment]
I have User ID and User Profile permission on App Manager under Data user Checkup but I have still the error -1006.
Why?
