### ISSUE TITLE
Does it work with Quest 1/2?

### ISSUE THREAD

**Issue by LB31** [oculus-samples/Unity-SharedSpatialAnchors#5]
The documentation says "Sharing anchors is only available on Meta Quest Pro headsets."
However, the Readme image implies that you also can use the previous headsets.

Which is true?

**Comment by yutokun** [comment]
This article said about that. Quset 2 will be supported in early 2023. Maybe Quest 1 will not.

https://developer.oculus.com/blog/build-local-multiplayer-experiences-shared-spatial-anchors/

**Comment by AdamRitenauer** [comment]
@LB31, @yutokun, To confirm: Shared Spatial Anchors is supported on Quest Pro, and will also be supported on Quest 2 in early 2023. There are no plans to support SSA on Quest 1.
