### ISSUE TITLE
getCloudPermissionEnabled: oculus_spatial_anchor_cloud=false

### ISSUE THREAD

**Issue by JulienCros** [oculus-samples/Unity-SharedSpatialAnchors#8]
Hello,

When creating an anchor and then sharing it, we come across an error on the app logs:

> "Saving anchor(s) failed. Possible reasons include an unsupported device."

![inHMD_error](https://user-images.githubusercontent.com/44341623/219074237-d773e72f-0b96-4dc5-944b-3ab3a18ce779.png)

When I check the adb logs, I get the following errors:

> SP:AP:AnchorPersistenceConfig: getCloudPermissionEnabled: oculus_spatial_anchor_cloud=false

> SP:AP:AnchorPersistenceRuntimeIpcServer: Request denied based on storage location for package com.Oculus.UnitySharedSpatialAnchors, sessionUuid:e0d791ec-49a1-4948-abd4-e4754812554b

> SP:AP:AnchorPersistenceRuntimeIpcServer: Aborting saveAnchorV3 for package name: com.Oculus.UnitySharedSpatialAnchors 

> SP:AP:AnchorPersistenceRuntimeIpcClient: Failed RPC for saveAnchor, rpcAllowed: false, CallServerRPCResult: 9 

> SP:AF:AnchorFrameworkSlamAnchor: saveAnchor failed!

![ADB_error](https://user-images.githubusercontent.com/44341623/219074231-717d1c92-cc43-46d0-8423-498fed105ba9.png)

Do you have any idea how to resolve this issue (I can't seem to find anything on internet) ? Could it come from a missing Android permission ?

**Comment by JulienCros** [comment]
> Thank you for reporting this issue. We are working on a fix. In the meantime, could you try the following mitigation?
> 
> 1. Make sure that the setting "Share point cloud data" is enabled? You can find this in Settings > Device Permissions > Share point cloud data (toggle). More information can be found at https://www.meta.com/help/quest/articles/in-vr-experiences/oculus-features/point-cloud/.
> 2. After ensuring that this setting is enabled, try rebooting the device and sharing the anchor again.

We had been making sure it was enabled everywhere before even having the error.
It now works well everywhere (we just lost the ability to save the anchors locally for no reason and I won't be able to look into it).

We're not sure but our best guess is that after getting the approval for the Data Use Checkup, it takes a few days to properly enable the right to access the Platform's Cloud.

The only other thing we changed the day it started working was requesting every Data Use Checkup permission directly or indirectly related to multiplayer. It then started working hours later on only one of our Test User but I think it may be only a coincidence. I created a new Test User for my other HMD Pro on which it everything worked right away.

Either way it definitely looks like a server issue.

Maybe I would suggest you to add to the guide that it is required to:
1)  Create an organisation and an app on the Platform's site
2) Add the AppID to Unity AND Photon
3) Request UserID (and Profile ID?) on the Data Use Checkup tab
4) Wait for a few days once getting approval ?

Also in the documentation about Test Users, it is said that they can allow to bypass the Data Use Checkup authorizations request and it is not the case.

You can close this issue if you want, if you have any other question I'll gladly answer it

**Comment by SteveOnorato** [comment]
Thanks for helping the developer community by reporting this and providing a solution!
The documentation at https://developer.oculus.com/documentation/unity/unity-ssa-sf/ has been updated.
