### ISSUE TITLE
OnShareCompleteResult : -1006

### ISSUE THREAD

**Issue by minaghobrial** [oculus-samples/Unity-SharedSpatialAnchors#9]
Hello,
I'm testing out the example on two Quest 2 headsets. Point Cloud Sharing is enabled on both headsets, they're both connected to the same router. When I create an anchor and share it, it does annouce that it was successfully shared to the cloud, the next line says OnShareCompleteResult : -1006, then the Share Anchor button becomes red and the anchor never appears to the other headset.

**Comment by stephenm2022** [comment]
Thank you for reporting this issue. We are working to improve the return result to include more information on -1006. 

You will need to create an app in the Meta Quest Org Manager and associate this app with the sample.

Please complete the following steps:
1. Create an app on the Meta Quest Org Manager: https://developer.oculus.com/resources/publish-intro/ 
2. Copy the App ID (found under "API" tab in App Manager) and add it to the OculusPlatformSettings.asset in the Unity sample.
3. Request User ID and User Profile permissions (found under "Data Use Checkup" tab in App Manager).
